title:              Zarpele Blog!
email:              guido.robertone@example.com
description:        A straightforward blog written by a human being.
author:             Guido F. Robertone
baseurl:            "/"
url:                "https://guidorobertone.github.io/zarpele"

# Social Profiles
twitter_username:   zarpele
github_username:    GuidoRobertone
facebook_username:
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
